### ISSUE TITLE
"git lint" issue on Windows machine

### ISSUE THREAD

**Issue by saurabhprakash** [sk-/git-lint#102]
For set of changed files in python, as soon as we run the "git lint" command, 

We're getting these error, 

```(virtual-env-folder) λ git lint

Linting file: webapp\apps\core\utils.py

SKIPPED: pylint is not installed. Run pip install pylint.

SKIPPED: pep8 is not installed. Run pip install pep8.
```

But the following setups were installed in both inside and outside virtual environment.

Please let us know if any specific action needs to be taken for windows machine?

**Comment by sk-** [comment]
This is because the configuration file is tailored for unix systems (i.e., the executables do not have the .exe extension).

You would need to fork the configuration file and adjust the names to what is used in Windows. I believe to run pylint you execute `pylint.exe`, so you would need to change https://github.com/sk-/git-lint/blob/master/gitlint/configs/config.yaml#L93 so that the command is now `python.exe`

**Comment by saurabhprakash** [comment]
Ohk. thanks
